package com.kmpstarter.theme

import androidx.compose.ui.graphics.Color

/*Light Color Scheme*/
val primaryLight = Color(0xFF3B82F6)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDBEAFE)
val onPrimaryContainerLight = Color(0xFF1E3A8A)
val secondaryLight = Color(0xFF6366F1)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE0E7FF)
val onSecondaryContainerLight = Color(0xFF312E81)
val tertiaryLight = Color(0xFF8B5CF6)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF3E8FF)
val onTertiaryContainerLight = Color(0xFF581C87)
val errorLight = Color(0xFFEF4444)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFEE2E2)
val onErrorContainerLight = Color(0xFF7F1D1D)
val backgroundLight = Color(0xFFF8FAFC)
val onBackgroundLight = Color(0xFF0F172A)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF0F172A)
val surfaceVariantLight = Color(0xFFF1F5F9)
val onSurfaceVariantLight = Color(0xFF334155)
val outlineLight = Color(0xFF64748B)
val outlineVariantLight = Color(0xFFCBD5E1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3036)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFFAAC7FF)
val surfaceDimLight = Color(0xFFD9D9E0)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3FA)
val surfaceContainerLight = Color(0xFFEDEDF4)
val surfaceContainerHighLight = Color(0xFFE7E8EE)
val surfaceContainerHighestLight = Color(0xFFE2E2E9)

/*Dark Color Scheme*/
val primaryDark = Color(0xFF60A5FA)
val onPrimaryDark = Color(0xFF1E3A8A)
val primaryContainerDark = Color(0xFF2563EB)
val onPrimaryContainerDark = Color(0xFFDBEAFE)
val secondaryDark = Color(0xFF818CF8)
val onSecondaryDark = Color(0xFF312E81)
val secondaryContainerDark = Color(0xFF4F46E5)
val onSecondaryContainerDark = Color(0xFFE0E7FF)
val tertiaryDark = Color(0xFFA78BFA)
val onTertiaryDark = Color(0xFF581C87)
val tertiaryContainerDark = Color(0xFF7C3AED)
val onTertiaryContainerDark = Color(0xFFF3E8FF)
val errorDark = Color(0xFFF87171)
val onErrorDark = Color(0xFF7F1D1D)
val errorContainerDark = Color(0xFFDC2626)
val onErrorContainerDark = Color(0xFFFEE2E2)
val backgroundDark = Color(0xFF0F172A)
val onBackgroundDark = Color(0xFFF8FAFC)
val surfaceDark = Color(0xFF1E293B)
val onSurfaceDark = Color(0xFFF8FAFC)
val surfaceVariantDark = Color(0xFF334155)
val onSurfaceVariantDark = Color(0xFFE2E8F0)
val outlineDark = Color(0xFF94A3B8)
val outlineVariantDark = Color(0xFF475569)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2E3036)
val inversePrimaryDark = Color(0xFF415F91)
val surfaceDimDark = Color(0xFF111318)
val surfaceBrightDark = Color(0xFF37393E)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF191C20)
val surfaceContainerDark = Color(0xFF1D2024)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF33353A)


/*Custom Light Color Scheme*/

/*Custom Dark Color Scheme*/

